app:
  message: Message has been sent Successfully..
spring:
  application:
    name: TransactionReportingSystem
  datasource:
    username: root
    password:   
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: user.exchange 
    queue: user.queue 
    routing-key: user.routingkey
    obligation-response-queue: obligation.queue 
server:
  port: 8200