spring:
  application:
    name: obligation
  datasource:
    username: root
    password:   
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: user.exchange
    queue: user.queue
    routingkey: user.routingkey
    generation-response-queue: generation.response.queue
    generation-exchange: generation.exchange
    generation-queue: generation.queue
    generation-routing-key: generation.routingkey
    
server:
  port: 8201
  